Added support for Ox inv and added webhook check
Project-Sloth/ps-camera pull request #18
Opened 2023-05-07 23:50 UTC by lenzh

Moved Webhook to Config.
Added Config.Inv for inventory support (qb ox)

2023-05-10 05:55 UTC, MonkeyWhisper requested changes

2023-05-10 05:55 UTC, MonkeyWhisper commented on config.lua
> +Config.webhook = "https://discord.com/api/webhooks/1098347143602913340/61nQVpgAZILNJyUNN3v6AP2yvtR8VLKcOjNVcfGYpKBfotrpqNy4uDxsQA-ERh4bqnFi" -- Add Discord webhook
Move this to server sided please, so people can't dump it
And leave it as default qb, and remove your webhook

Thanks!

2023-05-10 18:46 UTC, lenzh commented
Fixed on latest push

2023-05-14 21:05 UTC, xFutte commented on server/sv_main.lua
> +
```suggestion
if not (Config.Inv == "qb" or Config.Inv == "ox") then 
    ConfigInvInvalid()
    return;
end
```

and then extract the print to a new local function.

2023-05-14 21:12 UTC, xFutte approved these changes

2023-05-14 21:14 UTC, xFutte commented
Looks good to me. I'll let @MonkeyWhisper merge since he initially requested changes.

2023-05-14 21:16 UTC, xFutte commented
![image](https://github.com/Project-Sloth/ps-camera/assets/6727484/593d358b-26ee-440c-ae70-a0ecc2264e97)

Squash and merge it when merging.

2023-06-09 01:12 UTC, merged