Photo url copies to clipboard when taking a picture now
Project-Sloth/ps-camera pull request #21
Opened 2023-05-14 20:31 UTC by lenzh

2023-05-14 20:59 UTC, xFutte requested changes

2023-05-14 20:59 UTC, xFutte commented on client/nui/app.js
> +
Not a very good implementation, including that `document.execCommand()` has been deprecated. Have a look at https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard instead.

2023-05-14 21:14 UTC, xFutte commented
Looks good to me.

2023-06-09 01:12 UTC, merged

2023-06-10 10:00 UTC, xFutte commented
@MonkeyWhisper Why was this merged?

2023-06-10 14:44 UTC, MonkeyWhisper commented
> @MonkeyWhisper Why was this merged?

Shoot, I didn't see your comment above!